spring:
  datasource:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6684507
    username: sql6684507
    password: J2seZNm9mj
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    user:
      password: TestEC

# App Properties
app:
  jwtSecret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
  jwtExpirationMs: 86400000
